-- Boxoffice pipeline — warehouse, roles, service users (deliverable 2 of 8).
-- Run as ACCOUNTADMIN. Requires 01_database_and_schemas.sql to have run first.
--
-- Authorization model:
--   ACCOUNTADMIN — owner of everything (DB, schemas, WH, roles, users). Setup + bootstrap run as ACCOUNTADMIN.
--   SYSADMIN    — inherits the three functional roles (USE ROLE), but does NOT own them.
--   BOXOFFICE_AIRFLOW — Airflow EL: COPY INTO RAW from S3 stage.
--   BOXOFFICE_DBT     — dbt: read RAW, full DDL+DML on STAGING and MARTS.
--   BOXOFFICE_READ    — Power BI: SELECT only on MARTS.
--
-- Public keys for the three service users are loaded out-of-band (ALTER USER ... SET RSA_PUBLIC_KEY = '...')
-- after this script. Keys never enter the repo — see README "Loading public keys" section.

USE ROLE ACCOUNTADMIN;


CREATE WAREHOUSE IF NOT EXISTS BOXOFFICE_WH
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Single warehouse for the BOXOFFICE pipeline; sized small for trial credits.';


CREATE ROLE IF NOT EXISTS BOXOFFICE_AIRFLOW
  COMMENT = 'Airflow EL: COPY INTO RAW from S3 stage. Write to RAW only.';

CREATE ROLE IF NOT EXISTS BOXOFFICE_DBT
  COMMENT = 'dbt: read RAW, full DDL+DML on STAGING and MARTS.';

CREATE ROLE IF NOT EXISTS BOXOFFICE_READ
  COMMENT = 'Power BI: SELECT only on MARTS (read-only for the dashboard).';

GRANT ROLE BOXOFFICE_AIRFLOW TO ROLE SYSADMIN;
GRANT ROLE BOXOFFICE_DBT     TO ROLE SYSADMIN;
GRANT ROLE BOXOFFICE_READ    TO ROLE SYSADMIN;


CREATE USER IF NOT EXISTS BOXOFFICE_AIRFLOW_SVC
  TYPE = SERVICE
  DEFAULT_ROLE = BOXOFFICE_AIRFLOW
  DEFAULT_WAREHOUSE = BOXOFFICE_WH
  COMMENT = 'Airflow service user (Astronomer connection).';

CREATE USER IF NOT EXISTS BOXOFFICE_DBT_SVC
  TYPE = SERVICE
  DEFAULT_ROLE = BOXOFFICE_DBT
  DEFAULT_WAREHOUSE = BOXOFFICE_WH
  COMMENT = 'dbt service user (local dev + GitHub Actions).';

CREATE USER IF NOT EXISTS BOXOFFICE_READ_SVC
  TYPE = SERVICE
  DEFAULT_ROLE = BOXOFFICE_READ
  DEFAULT_WAREHOUSE = BOXOFFICE_WH
  COMMENT = 'Power BI service user (gateway / direct connector).';

GRANT ROLE BOXOFFICE_AIRFLOW TO USER BOXOFFICE_AIRFLOW_SVC;
GRANT ROLE BOXOFFICE_DBT     TO USER BOXOFFICE_DBT_SVC;
GRANT ROLE BOXOFFICE_READ    TO USER BOXOFFICE_READ_SVC;


GRANT USAGE ON WAREHOUSE BOXOFFICE_WH TO ROLE BOXOFFICE_AIRFLOW;
GRANT USAGE ON WAREHOUSE BOXOFFICE_WH TO ROLE BOXOFFICE_DBT;
GRANT USAGE ON WAREHOUSE BOXOFFICE_WH TO ROLE BOXOFFICE_READ;


GRANT USAGE ON DATABASE BOXOFFICE TO ROLE BOXOFFICE_AIRFLOW;
GRANT USAGE ON DATABASE BOXOFFICE TO ROLE BOXOFFICE_DBT;
GRANT USAGE ON DATABASE BOXOFFICE TO ROLE BOXOFFICE_READ;

GRANT USAGE ON SCHEMA BOXOFFICE.RAW  TO ROLE BOXOFFICE_AIRFLOW;
GRANT USAGE ON SCHEMA BOXOFFICE.UTIL TO ROLE BOXOFFICE_AIRFLOW;

GRANT USAGE ON SCHEMA BOXOFFICE.RAW     TO ROLE BOXOFFICE_DBT;
GRANT USAGE ON SCHEMA BOXOFFICE.STAGING TO ROLE BOXOFFICE_DBT;
GRANT USAGE ON SCHEMA BOXOFFICE.MARTS   TO ROLE BOXOFFICE_DBT;

GRANT USAGE ON SCHEMA BOXOFFICE.MARTS TO ROLE BOXOFFICE_READ;


GRANT CREATE TABLE, CREATE VIEW ON SCHEMA BOXOFFICE.STAGING TO ROLE BOXOFFICE_DBT;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA BOXOFFICE.MARTS   TO ROLE BOXOFFICE_DBT;


GRANT INSERT, SELECT ON FUTURE TABLES IN SCHEMA BOXOFFICE.RAW TO ROLE BOXOFFICE_AIRFLOW;
GRANT SELECT         ON FUTURE TABLES IN SCHEMA BOXOFFICE.RAW TO ROLE BOXOFFICE_DBT;

GRANT SELECT ON FUTURE TABLES IN SCHEMA BOXOFFICE.MARTS TO ROLE BOXOFFICE_READ;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA BOXOFFICE.MARTS TO ROLE BOXOFFICE_READ;
