-- Boxoffice pipeline — stored procedures as RBAC boundary (deliverable beyond BRIEF's 8 core).
-- Run as ACCOUNTADMIN. Prereqs: 01-06 (schemas, roles, raw tables, external table, log, view).
--
-- Creates:
--   BOXOFFICE.RAW.SP_COPY_REVENUES_FROM_RAW(p_file)     — wraps COPY INTO REVENUES from @S3_BOX_OFFICE
--   BOXOFFICE.RAW.SP_LOG_OMDB_CALL_BATCH(p_batch)        — wraps batched INSERT to OMDB_FETCH_LOG via FLATTEN
--   BOXOFFICE.RAW.SP_REFRESH_OMDB_CACHE()                — wraps ALTER EXTERNAL TABLE RAW.OMDB REFRESH

USE ROLE ACCOUNTADMIN;
USE DATABASE BOXOFFICE;
USE SCHEMA RAW;


GRANT OWNERSHIP ON EXTERNAL TABLE BOXOFFICE.RAW.OMDB TO ROLE ACCOUNTADMIN COPY CURRENT GRANTS;


CREATE OR REPLACE PROCEDURE BOXOFFICE.RAW.SP_COPY_REVENUES_FROM_RAW(p_file VARCHAR)
RETURNS NUMBER
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    sql_cmd VARCHAR;
    copy_status VARCHAR;
    rows_loaded NUMBER;
BEGIN
    sql_cmd := 'COPY INTO BOXOFFICE.RAW.REVENUES (ID, REVENUE_DATE, TITLE, REVENUE, THEATERS, DISTRIBUTOR, _SOURCE_FILE) ' ||
               'FROM (SELECT $1, $2, $3, $4, $5, $6, METADATA$FILENAME FROM @BOXOFFICE.UTIL.S3_BOX_OFFICE) ' ||
               'FILES = (''' || REPLACE(:p_file, '''', '''''') || ''') ' ||
               'FILE_FORMAT = (FORMAT_NAME = BOXOFFICE.UTIL.CSV_STANDARD) ' ||
               'ON_ERROR = ABORT_STATEMENT';
    EXECUTE IMMEDIATE :sql_cmd;

    SELECT $2, $4 INTO :copy_status, :rows_loaded
    FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
    LIMIT 1;

    IF (:copy_status != 'LOADED') THEN
        RAISE STATEMENT_ERROR;
    END IF;

    RETURN :rows_loaded;
END;
$$;


CREATE OR REPLACE PROCEDURE BOXOFFICE.RAW.SP_LOG_OMDB_CALL_BATCH(p_batch VARIANT)
RETURNS STRING
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN
    INSERT INTO BOXOFFICE.RAW.OMDB_FETCH_LOG
    (lookup_title, lookup_year, outcome, http_status, error_message)
    SELECT
        v.value:lookup_title::VARCHAR,
        v.value:lookup_year::NUMBER(4,0),
        v.value:outcome::VARCHAR,
        v.value:http_status::NUMBER(3,0),
        v.value:error_message::VARCHAR
    FROM TABLE(FLATTEN(input => :p_batch)) v;
    RETURN 'OK';
END;
$$;


CREATE OR REPLACE PROCEDURE BOXOFFICE.RAW.SP_REFRESH_OMDB_CACHE()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN
    ALTER EXTERNAL TABLE BOXOFFICE.RAW.OMDB REFRESH;
    RETURN 'OK';
END;
$$;


GRANT USAGE ON PROCEDURE BOXOFFICE.RAW.SP_COPY_REVENUES_FROM_RAW(VARCHAR) TO ROLE BOXOFFICE_AIRFLOW;
GRANT USAGE ON PROCEDURE BOXOFFICE.RAW.SP_LOG_OMDB_CALL_BATCH(VARIANT)   TO ROLE BOXOFFICE_AIRFLOW;
GRANT USAGE ON PROCEDURE BOXOFFICE.RAW.SP_REFRESH_OMDB_CACHE()           TO ROLE BOXOFFICE_AIRFLOW;

